#include "portal.h"
#include "mongoose.h"
#include <stdlib.h>
#include <string.h>

/* ─── GET /ui  ──────────────────────────────────────────────────────────── */

void handle_portal(struct mg_connection *c, struct mg_http_message *hm, DbConn *db) {
    (void)hm; (void)db;

    static const char HTML[] =
"<!DOCTYPE html>\n"
"<html lang='ja'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width,initial-scale=1'>\n"
"<title>Asoview — 体験・アクティビティ予約</title>\n"
"<style>\n"
":root{"
"--bg:#09090f;--surface:#111118;--card:#16161f;--border:#222232;"
"--accent:#7c3aed;--accent2:#a855f7;--text:#f0f0f8;--muted:#888;--sub:#555;"
"--success:#10b981;--danger:#ef4444;--warn:#f59e0b;"
"}\n"
"*{box-sizing:border-box;margin:0;padding:0;}\n"
"body{background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,sans-serif;min-height:100vh;}\n"
"a{color:inherit;text-decoration:none;}\n"
"button{cursor:pointer;border:none;font-family:inherit;}\n"
"input,select,textarea{font-family:inherit;}\n"

/* HEADER */
"header{background:var(--surface);border-bottom:1px solid var(--border);padding:0 24px;height:56px;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:50;}\n"
"header .logo{font-size:18px;font-weight:800;background:linear-gradient(135deg,var(--accent),var(--accent2));-webkit-background-clip:text;-webkit-text-fill-color:transparent;cursor:pointer;}\n"
"header nav{display:flex;gap:8px;align-items:center;}\n"
"header nav a{padding:6px 12px;border-radius:6px;font-size:13px;color:var(--muted);transition:color .15s,background .15s;}\n"
"header nav a:hover,header nav a.active{color:var(--text);background:var(--card);}\n"
".btn{padding:8px 18px;border-radius:8px;font-size:13px;font-weight:600;transition:opacity .15s;}\n"
".btn:hover{opacity:.85;}\n"
".btn-primary{background:var(--accent);color:#fff;}\n"
".btn-ghost{background:transparent;border:1px solid var(--border);color:var(--text);}\n"
".btn-danger{background:var(--danger);color:#fff;}\n"
".btn-sm{padding:5px 12px;font-size:12px;}\n"

/* HERO */
"#hero{background:linear-gradient(135deg,#13001f 0%,#0d0030 50%,#09090f 100%);padding:60px 24px 48px;text-align:center;}\n"
"#hero h1{font-size:clamp(28px,5vw,52px);font-weight:900;line-height:1.1;margin-bottom:12px;}\n"
"#hero h1 span{background:linear-gradient(135deg,var(--accent),var(--accent2),#ec4899);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}\n"
"#hero p{color:var(--muted);font-size:15px;margin-bottom:28px;}\n"
"#hero .search-bar{display:flex;gap:8px;max-width:640px;margin:0 auto;}\n"
"#hero .search-bar input{flex:1;background:var(--surface);border:1px solid var(--border);color:var(--text);padding:12px 16px;border-radius:10px;font-size:14px;outline:none;}\n"
"#hero .search-bar input:focus{border-color:var(--accent);}\n"
"#hero .search-bar button{padding:12px 24px;}\n"

/* FILTER BAR */
"#filter-bar{background:var(--surface);border-bottom:1px solid var(--border);padding:10px 24px;display:flex;gap:10px;align-items:center;flex-wrap:wrap;overflow-x:auto;}\n"
"#filter-bar select{background:var(--card);border:1px solid var(--border);color:var(--text);padding:7px 12px;border-radius:8px;font-size:13px;outline:none;}\n"
"#filter-bar select:focus{border-color:var(--accent);}\n"
".chip{background:var(--card);border:1px solid var(--border);color:var(--muted);padding:6px 14px;border-radius:20px;font-size:12px;cursor:pointer;transition:all .15s;white-space:nowrap;}\n"
".chip.active{background:var(--accent);color:#fff;border-color:var(--accent);}\n"

/* MAIN LAYOUT */
"#page{max-width:1200px;margin:0 auto;padding:24px;}\n"

/* PLAN GRID */
"#plans-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px;}\n"
".plan-card{background:var(--card);border:1px solid var(--border);border-radius:12px;overflow:hidden;cursor:pointer;transition:transform .2s,box-shadow .2s;}\n"
".plan-card:hover{transform:translateY(-3px);box-shadow:0 8px 32px rgba(124,58,237,.2);}\n"
".plan-card .thumb{width:100%;height:160px;background:linear-gradient(135deg,#1a0533,#0d1b33);display:flex;align-items:center;justify-content:center;font-size:40px;overflow:hidden;}\n"
".plan-card .thumb img{width:100%;height:100%;object-fit:cover;}\n"
".plan-card .body{padding:14px;}\n"
".plan-card .cat{font-size:11px;color:var(--accent2);text-transform:uppercase;letter-spacing:.5px;margin-bottom:4px;}\n"
".plan-card h3{font-size:14px;font-weight:700;margin-bottom:6px;line-height:1.3;}\n"
".plan-card .venue{font-size:12px;color:var(--muted);margin-bottom:8px;}\n"
".plan-card .foot{display:flex;align-items:center;justify-content:space-between;}\n"
".plan-card .price{font-size:15px;font-weight:700;color:var(--accent2);}\n"
".plan-card .rating{font-size:12px;color:var(--warn);}\n"

/* DETAIL VIEW */
"#detail-view{display:none;}\n"
"#detail-view .hero-img{width:100%;height:280px;background:linear-gradient(135deg,#1a0533,#0d1b33);border-radius:12px;margin-bottom:20px;display:flex;align-items:center;justify-content:center;font-size:60px;overflow:hidden;}\n"
"#detail-view .hero-img img{width:100%;height:100%;object-fit:cover;}\n"
"#detail-view .layout{display:grid;grid-template-columns:1fr 320px;gap:24px;}\n"
"@media(max-width:768px){#detail-view .layout{grid-template-columns:1fr;}}\n"
"#detail-view h1{font-size:24px;font-weight:800;margin-bottom:8px;}\n"
"#detail-view .meta{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:16px;}\n"
"#detail-view .meta span{font-size:12px;color:var(--muted);background:var(--card);padding:4px 10px;border-radius:20px;}\n"
"#detail-view .desc{font-size:14px;color:var(--muted);line-height:1.7;margin-bottom:20px;}\n"
"#detail-view .cancel-policy{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:12px;margin-bottom:20px;}\n"
"#detail-view .cancel-policy h4{font-size:12px;color:var(--accent2);margin-bottom:6px;}\n"
"#detail-view .cancel-policy p{font-size:12px;color:var(--muted);}\n"

/* BOOKING BOX */
".booking-box{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:20px;position:sticky;top:72px;}\n"
".booking-box h3{font-size:16px;font-weight:700;margin-bottom:16px;}\n"
".booking-box .price-display{font-size:24px;font-weight:900;color:var(--accent2);margin-bottom:16px;}\n"
".form-group{margin-bottom:12px;}\n"
".form-group label{display:block;font-size:12px;color:var(--muted);margin-bottom:5px;}\n"
".form-group input,.form-group select,.form-group textarea{width:100%;background:var(--card);border:1px solid var(--border);color:var(--text);padding:9px 12px;border-radius:8px;font-size:13px;outline:none;}\n"
".form-group input:focus,.form-group select:focus{border-color:var(--accent);}\n"
".participants-row{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px;}\n"
".participants-row .label{font-size:13px;}\n"
".participants-row .qty{display:flex;align-items:center;gap:8px;}\n"
".qty-btn{width:28px;height:28px;background:var(--card);border:1px solid var(--border);color:var(--text);border-radius:6px;font-size:16px;}\n"
".qty-num{font-size:14px;font-weight:700;min-width:20px;text-align:center;}\n"
".price-summary{background:var(--card);border-radius:8px;padding:12px;margin:12px 0;font-size:13px;}\n"
".price-row{display:flex;justify-content:space-between;margin-bottom:4px;color:var(--muted);}\n"
".price-row.total{color:var(--text);font-weight:700;border-top:1px solid var(--border);margin-top:8px;padding-top:8px;}\n"
".coupon-row{display:flex;gap:6px;margin-bottom:4px;}\n"
".coupon-row input{flex:1;}\n"
".coupon-row button{white-space:nowrap;}\n"
".coupon-applied{font-size:12px;color:var(--success);margin-top:4px;}\n"
".coupon-error{font-size:12px;color:var(--danger);margin-top:4px;}\n"

/* MY BOOKINGS */
"#bookings-view{display:none;}\n"
".booking-item{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:16px;margin-bottom:12px;display:flex;gap:16px;align-items:flex-start;}\n"
".booking-item .info{flex:1;}\n"
".booking-item .title{font-size:14px;font-weight:700;margin-bottom:4px;}\n"
".booking-item .detail{font-size:12px;color:var(--muted);}\n"
".badge{display:inline-block;padding:2px 10px;border-radius:20px;font-size:11px;font-weight:600;}\n"
".badge-confirmed{background:#0d2b1d;color:var(--success);}\n"
".badge-cancelled{background:#2a0d0d;color:var(--danger);}\n"
".badge-pending{background:#2a1f00;color:var(--warn);}\n"

/* REVIEWS */
".review-item{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:14px;margin-bottom:10px;}\n"
".review-item .stars{color:var(--warn);font-size:13px;margin-bottom:4px;}\n"
".review-item .comment{font-size:13px;color:var(--muted);}\n"
".review-item .author{font-size:11px;color:var(--sub);margin-top:6px;}\n"

/* MODAL */
".overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.75);z-index:200;justify-content:center;align-items:center;padding:20px;}\n"
".overlay.open{display:flex;}\n"
".modal{background:var(--surface);border:1px solid var(--border);border-radius:14px;padding:28px;width:100%;max-width:420px;}\n"
".modal h2{font-size:20px;font-weight:800;margin-bottom:6px;}\n"
".modal .sub{font-size:13px;color:var(--muted);margin-bottom:20px;}\n"
".modal-tabs{display:flex;gap:4px;margin-bottom:20px;border-bottom:1px solid var(--border);}\n"
".modal-tabs button{padding:8px 16px;background:none;color:var(--muted);font-size:13px;border-radius:6px 6px 0 0;border-bottom:2px solid transparent;}\n"
".modal-tabs button.active{color:var(--text);border-bottom-color:var(--accent);}\n"
".msg{padding:8px 12px;border-radius:6px;font-size:13px;margin-bottom:12px;}\n"
".msg.ok{background:#0d2b1d;color:var(--success);}\n"
".msg.err{background:#2a0d0d;color:var(--danger);}\n"

/* LOADING */
".spinner{border:3px solid var(--border);border-top-color:var(--accent);border-radius:50%;width:32px;height:32px;animation:spin .7s linear infinite;margin:40px auto;}\n"
"@keyframes spin{to{transform:rotate(360deg);}}\n"
".empty{text-align:center;padding:48px 20px;color:var(--muted);}\n"
".empty .icon{font-size:40px;margin-bottom:12px;}\n"

/* TOAST */
"#toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:var(--surface);border:1px solid var(--border);padding:12px 20px;border-radius:10px;font-size:13px;z-index:999;opacity:0;transition:opacity .3s;pointer-events:none;}\n"
"#toast.show{opacity:1;}\n"

/* BACK BUTTON */
".back-btn{display:inline-flex;align-items:center;gap:6px;color:var(--muted);font-size:13px;margin-bottom:20px;cursor:pointer;}\n"
".back-btn:hover{color:var(--text);}\n"

/* WAITLIST */
".waitlist-box{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:16px;text-align:center;margin-top:8px;}\n"
".waitlist-box p{font-size:14px;color:var(--muted);margin-bottom:10px;}\n"
"</style>\n"
"</head>\n"
"<body>\n"

/* HEADER */
"<header>\n"
"  <div class='logo' onclick='showView(\"home\")'>&#9965; Asoview</div>\n"
"  <nav>\n"
"    <a href='#' onclick='showView(\"home\")' id='nav-home'>プランを探す</a>\n"
"    <a href='#' onclick='showBookings()' id='nav-bookings'>マイ予約</a>\n"
"  </nav>\n"
"  <div id='auth-area'>\n"
"    <button class='btn btn-ghost btn-sm' onclick='openAuth(\"login\")' id='btn-login'>ログイン</button>\n"
"    <button class='btn btn-primary btn-sm' onclick='openAuth(\"register\")' id='btn-register' style='margin-left:6px;'>新規登録</button>\n"
"    <div id='user-menu' style='display:none;position:relative;'>\n"
"      <button class='btn btn-ghost btn-sm' onclick='toggleUserMenu()' id='user-name-btn'></button>\n"
"      <div id='user-dropdown' style='display:none;position:absolute;right:0;top:36px;background:var(--surface);border:1px solid var(--border);border-radius:8px;padding:4px;min-width:140px;'>\n"
"        <div style='padding:8px 12px;font-size:12px;color:var(--muted);border-bottom:1px solid var(--border);' id='user-email-display'></div>\n"
"        <button onclick='showBookings()' style='display:block;width:100%;text-align:left;padding:8px 12px;background:none;color:var(--text);font-size:13px;border-radius:4px;'>マイ予約</button>\n"
"        <button onclick='logout()' style='display:block;width:100%;text-align:left;padding:8px 12px;background:none;color:var(--danger);font-size:13px;border-radius:4px;'>ログアウト</button>\n"
"      </div>\n"
"    </div>\n"
"  </div>\n"
"</header>\n"

/* HOME VIEW */
"<div id='home-view'>\n"
"  <div id='hero'>\n"
"    <h1>体験で、<span>思い出を作ろう</span></h1>\n"
"    <p>日本全国のアクティビティ・体験プランを検索・予約</p>\n"
"    <div class='search-bar'>\n"
"      <input type='text' id='search-input' placeholder='キーワード（例: シュノーケル、SUP、陶芸...）' onkeydown='if(event.key===\"Enter\")doSearch()'>\n"
"      <button class='btn btn-primary' onclick='doSearch()'>&#128269; 検索</button>\n"
"    </div>\n"
"  </div>\n"
"  <div id='filter-bar'>\n"
"    <select id='filter-area' onchange='loadPlans()'><option value=''>全エリア</option></select>\n"
"    <select id='filter-cat' onchange='loadPlans()'><option value=''>全カテゴリ</option></select>\n"
"    <input type='date' id='filter-date' onchange='loadPlans()' style='background:var(--card);border:1px solid var(--border);color:var(--text);padding:7px 12px;border-radius:8px;font-size:13px;outline:none;'>\n"
"  </div>\n"
"  <div id='page'>\n"
"    <div id='plans-grid'><div class='spinner'></div></div>\n"
"  </div>\n"
"</div>\n"

/* DETAIL VIEW */
"<div id='detail-view'>\n"
"  <div id='page' style='max-width:1200px;margin:0 auto;padding:24px;'>\n"
"    <div class='back-btn' onclick='showView(\"home\")'>&#8592; 一覧に戻る</div>\n"
"    <div id='detail-hero-img' class='hero-img'><span>&#127754;</span></div>\n"
"    <div class='layout'>\n"
"      <div id='detail-left'></div>\n"
"      <div>\n"
"        <div class='booking-box' id='booking-box'>\n"
"          <h3>予約する</h3>\n"
"          <div class='price-display' id='book-base-price'></div>\n"
"          <div class='form-group'>\n"
"            <label>日程を選択</label>\n"
"            <select id='book-schedule' onchange='updateSummary()'><option value=''>読み込み中...</option></select>\n"
"          </div>\n"
"          <div id='book-participants'></div>\n"
"          <div id='waitlist-section' style='display:none;'></div>\n"
"          <div class='form-group'>\n"
"            <label>クーポンコード（任意）</label>\n"
"            <div class='coupon-row'>\n"
"              <input type='text' id='coupon-input' placeholder='例: SUMMER20'>\n"
"              <button class='btn btn-ghost btn-sm' onclick='applyCoupon()'>適用</button>\n"
"            </div>\n"
"            <div id='coupon-msg'></div>\n"
"          </div>\n"
"          <div class='form-group'>\n"
"            <label>ギフトカードコード（任意）</label>\n"
"            <div class='coupon-row'>\n"
"              <input type='text' id='giftcard-input' placeholder='例: GIFT-XXXX-XXXX'>\n"
"              <button class='btn btn-ghost btn-sm' onclick='applyGiftCard()'>適用</button>\n"
"            </div>\n"
"            <div id='giftcard-msg'></div>\n"
"          </div>\n"
"          <div class='form-group'>\n"
"            <label>ご要望・メモ（任意）</label>\n"
"            <textarea id='book-note' rows='2' style='resize:vertical;'></textarea>\n"
"          </div>\n"
"          <div class='price-summary' id='book-summary'></div>\n"
"          <button class='btn btn-primary' style='width:100%;padding:12px;font-size:15px;' onclick='doBook()'>予約を確定する</button>\n"
"          <div id='book-msg' style='margin-top:8px;'></div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"    <div id='reviews-section' style='margin-top:32px;'></div>\n"
"  </div>\n"
"</div>\n"

/* BOOKINGS VIEW */
"<div id='bookings-view'>\n"
"  <div id='page' style='max-width:800px;margin:0 auto;padding:24px;'>\n"
"    <div class='back-btn' onclick='showView(\"home\")'>&#8592; プラン一覧へ</div>\n"
"    <h2 style='font-size:22px;font-weight:800;margin-bottom:20px;'>マイ予約</h2>\n"
"    <div id='my-bookings-list'><div class='spinner'></div></div>\n"
"  </div>\n"
"</div>\n"

/* AUTH MODAL */
"<div class='overlay' id='auth-modal'>\n"
"  <div class='modal'>\n"
"    <h2 id='auth-title'>ようこそ</h2>\n"
"    <div class='modal-tabs'>\n"
"      <button id='tab-login' class='active' onclick='switchAuthTab(\"login\")'>ログイン</button>\n"
"      <button id='tab-register' onclick='switchAuthTab(\"register\")'>新規登録</button>\n"
"      <button id='tab-reset' onclick='switchAuthTab(\"reset\")'>パスワードリセット</button>\n"
"    </div>\n"
"    <div id='auth-msg'></div>\n"
"    <!-- Login -->\n"
"    <div id='login-form'>\n"
"      <div class='form-group'><label>メールアドレス</label><input type='email' id='login-email' placeholder='you@example.com'></div>\n"
"      <div class='form-group'><label>パスワード</label><input type='password' id='login-pass' placeholder='••••••••' onkeydown='if(event.key===\"Enter\")doLogin()'></div>\n"
"      <button class='btn btn-primary' style='width:100%;padding:11px;' onclick='doLogin()'>ログイン</button>\n"
"    </div>\n"
"    <!-- Register -->\n"
"    <div id='register-form' style='display:none;'>\n"
"      <div class='form-group'><label>名前</label><input type='text' id='reg-name' placeholder='山田 太郎'></div>\n"
"      <div class='form-group'><label>メールアドレス</label><input type='email' id='reg-email' placeholder='you@example.com'></div>\n"
"      <div class='form-group'><label>パスワード（8文字以上）</label><input type='password' id='reg-pass' placeholder='••••••••' onkeydown='if(event.key===\"Enter\")doRegister()'></div>\n"
"      <button class='btn btn-primary' style='width:100%;padding:11px;' onclick='doRegister()'>アカウントを作成</button>\n"
"    </div>\n"
"    <!-- Password Reset -->\n"
"    <div id='reset-form' style='display:none;'>\n"
"      <p class='sub' style='margin-bottom:14px;'>登録済みのメールアドレスを入力してください。リセット用リンクをお送りします。</p>\n"
"      <div class='form-group'><label>メールアドレス</label><input type='email' id='reset-email' placeholder='you@example.com' onkeydown='if(event.key===\"Enter\")doForgotPassword()'></div>\n"
"      <button class='btn btn-primary' style='width:100%;padding:11px;' onclick='doForgotPassword()'>リセットメールを送信</button>\n"
"    </div>\n"
"    <button class='btn btn-ghost' style='width:100%;margin-top:10px;padding:10px;' onclick='closeModal(\"auth-modal\")'>閉じる</button>\n"
"  </div>\n"
"</div>\n"

/* RESCHEDULE MODAL */
"<div class='overlay' id='reschedule-modal'>\n"
"  <div class='modal'>\n"
"    <h2>日程を変更</h2>\n"
"    <p class='sub'>新しい日程を選んでください</p>\n"
"    <div id='reschedule-msg'></div>\n"
"    <input type='hidden' id='reschedule-booking-id'>\n"
"    <input type='hidden' id='reschedule-plan-id'>\n"
"    <div class='form-group'>\n"
"      <label>新しいスケジュール</label>\n"
"      <select id='reschedule-schedule'><option value=''>読み込み中...</option></select>\n"
"    </div>\n"
"    <div style='display:flex;gap:8px;margin-top:16px;'>\n"
"      <button class='btn btn-ghost' style='flex:1;' onclick='closeModal(\"reschedule-modal\")'>キャンセル</button>\n"
"      <button class='btn btn-primary' style='flex:1;' onclick='doReschedule()'>変更確定</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"

/* REVIEW MODAL */
"<div class='overlay' id='review-modal'>\n"
"  <div class='modal'>\n"
"    <h2>レビューを書く</h2>\n"
"    <div id='review-msg'></div>\n"
"    <input type='hidden' id='review-plan-id'>\n"
"    <div class='form-group'>\n"
"      <label>評価</label>\n"
"      <div id='star-picker' style='font-size:28px;display:flex;gap:4px;cursor:pointer;'>"
"<span onclick='setStar(1)'>&#9733;</span>"
"<span onclick='setStar(2)'>&#9733;</span>"
"<span onclick='setStar(3)'>&#9733;</span>"
"<span onclick='setStar(4)'>&#9733;</span>"
"<span onclick='setStar(5)'>&#9733;</span>"
"</div>\n"
"    </div>\n"
"    <div class='form-group'><label>コメント（任意）</label><textarea id='review-comment' rows='3'></textarea></div>\n"
"    <div style='display:flex;gap:8px;margin-top:16px;'>\n"
"      <button class='btn btn-ghost' style='flex:1;' onclick='closeModal(\"review-modal\")'>キャンセル</button>\n"
"      <button class='btn btn-primary' style='flex:1;' onclick='doReview()'>投稿する</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"

/* TOAST */
"<div id='toast'></div>\n"

"<script>\n"
"const API = '';\n"
"let currentPlan = null;\n"
"let currentView = 'home';\n"
"let starRating = 0;\n"
"let appliedCoupon = null;\n"
"let appliedGiftCard = null;\n"
"let firstScheduleId = null;\n"

/* ── Auth ── */
"function getToken(){return localStorage.getItem('token');}\n"
"function getUser(){try{return JSON.parse(localStorage.getItem('user'));}catch{return null;}}\n"
"function isLoggedIn(){return !!getToken();}\n"

"function updateAuthUI(){\n"
"  const u=getUser();\n"
"  if(u){\n"
"    document.getElementById('btn-login').style.display='none';\n"
"    document.getElementById('btn-register').style.display='none';\n"
"    document.getElementById('user-menu').style.display='block';\n"
"    document.getElementById('user-name-btn').textContent=(u.name||u.email)+'\\u25BE';\n"
"    document.getElementById('user-email-display').textContent=u.email||'';\n"
"  } else {\n"
"    document.getElementById('btn-login').style.display='';\n"
"    document.getElementById('btn-register').style.display='';\n"
"    document.getElementById('user-menu').style.display='none';\n"
"  }\n"
"}\n"

"function toggleUserMenu(){\n"
"  const d=document.getElementById('user-dropdown');\n"
"  d.style.display=d.style.display==='none'?'block':'none';\n"
"}\n"
"document.addEventListener('click',function(e){\n"
"  if(!document.getElementById('user-menu').contains(e.target)){\n"
"    document.getElementById('user-dropdown').style.display='none';\n"
"  }\n"
"});\n"

"function openAuth(tab){\n"
"  switchAuthTab(tab);\n"
"  openModal('auth-modal');\n"
"}\n"
"function switchAuthTab(tab){\n"
"  document.getElementById('login-form').style.display=tab==='login'?'':'none';\n"
"  document.getElementById('register-form').style.display=tab==='register'?'':'none';\n"
"  document.getElementById('reset-form').style.display=tab==='reset'?'':'none';\n"
"  document.getElementById('tab-login').className=tab==='login'?'active':'';\n"
"  document.getElementById('tab-register').className=tab==='register'?'active':'';\n"
"  document.getElementById('tab-reset').className=tab==='reset'?'active':'';\n"
"  showMsg('auth-msg','','');\n"
"}\n"

"async function doLogin(){\n"
"  const email=document.getElementById('login-email').value.trim();\n"
"  const pass=document.getElementById('login-pass').value;\n"
"  if(!email||!pass){showMsg('auth-msg','err','メールとパスワードを入力してください');return;}\n"
"  const r=await api('POST','/api/v1/auth/login',{email,password:pass});\n"
"  if(r.token){\n"
"    localStorage.setItem('token',r.token);\n"
"    localStorage.setItem('user',JSON.stringify(r.user||{email}));\n"
"    closeModal('auth-modal');\n"
"    updateAuthUI();\n"
"    toast('ログインしました');\n"
"  } else {\n"
"    showMsg('auth-msg','err',r.error||'ログインに失敗しました');\n"
"  }\n"
"}\n"

"async function doRegister(){\n"
"  const name=document.getElementById('reg-name').value.trim();\n"
"  const email=document.getElementById('reg-email').value.trim();\n"
"  const pass=document.getElementById('reg-pass').value;\n"
"  if(!name||!email||!pass){showMsg('auth-msg','err','すべての項目を入力してください');return;}\n"
"  const r=await api('POST','/api/v1/users',{name,email,password:pass});\n"
"  if(r.id||r.token){\n"
"    if(r.token){\n"
"      localStorage.setItem('token',r.token);\n"
"      localStorage.setItem('user',JSON.stringify(r.user||{name,email}));\n"
"      closeModal('auth-modal'); updateAuthUI(); toast('登録完了！');\n"
"    } else {\n"
"      switchAuthTab('login');\n"
"      showMsg('auth-msg','ok','登録完了！ログインしてください');\n"
"    }\n"
"  } else {\n"
"    showMsg('auth-msg','err',r.error||'登録に失敗しました');\n"
"  }\n"
"}\n"

"async function doForgotPassword(){\n"
"  const email=document.getElementById('reset-email').value.trim();\n"
"  if(!email){showMsg('auth-msg','err','メールアドレスを入力してください');return;}\n"
"  const r=await api('POST','/api/v1/auth/forgot-password',{email});\n"
"  if(r.error){\n"
"    showMsg('auth-msg','err',r.error||'送信に失敗しました');\n"
"  } else {\n"
"    showMsg('auth-msg','ok','リセット用メールを送信しました。受信トレイをご確認ください。');\n"
"    document.getElementById('reset-email').value='';\n"
"  }\n"
"}\n"

"function logout(){\n"
"  api('POST','/api/v1/auth/logout',{});\n"
"  localStorage.removeItem('token'); localStorage.removeItem('user');\n"
"  updateAuthUI(); showView('home'); toast('ログアウトしました');\n"
"}\n"

/* ── API helper ── */
"async function api(method,path,body,expectBlob){\n"
"  const headers={'Content-Type':'application/json'};\n"
"  const token=getToken();\n"
"  if(token) headers['Authorization']='Bearer '+token;\n"
"  const opts={method,headers};\n"
"  if(body&&method!=='GET') opts.body=JSON.stringify(body);\n"
"  try{\n"
"    const r=await fetch(API+path,opts);\n"
"    if(r.status===204) return {};\n"
"    const ct=r.headers.get('content-type')||'';\n"
"    if(ct.includes('json')) return r.json();\n"
"    return {_text: await r.text()};\n"
"  }catch(e){return {error:e.message};}\n"
"}\n"

/* ── View switching ── */
"function showView(v){\n"
"  document.getElementById('home-view').style.display=v==='home'?'':'none';\n"
"  document.getElementById('detail-view').style.display=v==='detail'?'':'none';\n"
"  document.getElementById('bookings-view').style.display=v==='bookings'?'':'none';\n"
"  currentView=v;\n"
"  document.getElementById('nav-home').className=v==='home'?'active':'';\n"
"  document.getElementById('nav-bookings').className=v==='bookings'?'active':'';\n"
"  window.scrollTo(0,0);\n"
"}\n"

/* ── Plans ── */
"async function loadPlans(){\n"
"  const grid=document.getElementById('plans-grid');\n"
"  grid.innerHTML='<div class=\"spinner\"></div>';\n"
"  const area=document.getElementById('filter-area').value;\n"
"  const cat=document.getElementById('filter-cat').value;\n"
"  const date=document.getElementById('filter-date').value;\n"
"  const kw=document.getElementById('search-input').value.trim();\n"
"  let url='/api/v1/plans?limit=48';\n"
"  if(area) url+='&area_id='+area;\n"
"  if(cat) url+='&category_id='+cat;\n"
"  if(date) url+='&date='+date;\n"
"  if(kw) url='/api/v1/search?q='+encodeURIComponent(kw)+'&limit=48';\n"
"  const d=await api('GET',url);\n"
"  const plans=d.plans||d.results||[];\n"
"  if(!plans.length){grid.innerHTML='<div class=\"empty\"><div class=\"icon\">&#127757;</div><p>プランが見つかりませんでした</p></div>';return;}\n"
"  grid.innerHTML=plans.map(planCard).join('');\n"
"}\n"

"function planCard(p){\n"
"  const price=p.prices&&p.prices.length?p.prices.reduce((mn,x)=>Math.min(mn,x.price),Infinity):0;\n"
"  const priceStr=price<Infinity?'¥'+price.toLocaleString()+'〜':'---';\n"
"  const img=p.images&&p.images.length?`<img src='${p.images[0]}' alt='' loading='lazy'>`:'<span>&#127754;</span>';\n"
"  const stars='&#9733;'.repeat(Math.round(p.avg_rating||0))+'&#9734;'.repeat(5-Math.round(p.avg_rating||0));\n"
"  return `<div class='plan-card' onclick='openPlan(${p.id})'>"
"<div class='thumb'>${img}</div>"
"<div class='body'>"
"<div class='cat'>${p.category_name||''}</div>"
"<h3>${p.title}</h3>"
"<div class='venue'>&#128205; ${p.venue_name||''}</div>"
"<div class='foot'>"
"<div class='price'>${priceStr}</div>"
"<div class='rating'>${stars} ${p.avg_rating?p.avg_rating.toFixed(1):''}</div>"
"</div></div></div>`;\n"
"}\n"

"async function openPlan(id){\n"
"  showView('detail');\n"
"  appliedCoupon=null;\n"
"  appliedGiftCard=null;\n"
"  firstScheduleId=null;\n"
"  document.getElementById('coupon-input').value='';\n"
"  document.getElementById('coupon-msg').innerHTML='';\n"
"  document.getElementById('giftcard-input').value='';\n"
"  document.getElementById('giftcard-msg').innerHTML='';\n"
"  const d=document.getElementById('detail-left');\n"
"  d.innerHTML='<div class=\"spinner\"></div>';\n"
"  const p=await api('GET','/api/v1/plans/'+id);\n"
"  currentPlan=p;\n"
"  const heroEl=document.getElementById('detail-hero-img');\n"
"  heroEl.innerHTML=p.images&&p.images.length?`<img src='${p.images[0]}' alt=''>`:'<span>&#127754;</span>';\n"
"  const price=p.prices&&p.prices.length?p.prices.reduce((mn,x)=>Math.min(mn,x.price),Infinity):0;\n"
"  document.getElementById('book-base-price').textContent=price<Infinity?'¥'+price.toLocaleString()+'〜':'価格未設定';\n"
"  const meta=[p.category_name,p.venue_name,p.duration_minutes?p.duration_minutes+'分':null,p.min_participants+'名〜'].filter(Boolean);\n"
"  const cancelInfo=buildCancelInfo(p);\n"
"  d.innerHTML=`<h1>${p.title}</h1>"
"<div class='meta'>${meta.map(m=>`<span>${m}</span>`).join('')}</div>"
"<p class='desc'>${p.description||'説明なし'}</p>"
"${cancelInfo}`;\n"
"  await loadSchedulesForPlan(id);\n"
"  buildParticipants(p.prices||[]);\n"
"  await loadReviews(id);\n"
"}\n"

"function buildCancelInfo(p){\n"
"  if(!p.cancel_days_full&&!p.cancel_days_partial) return '';\n"
"  let txt='';\n"
"  if(p.cancel_days_full) txt+=`${p.cancel_days_full}日前まで全額返金。`;\n"
"  if(p.cancel_days_partial&&p.cancel_pct_partial) txt+=`${p.cancel_days_partial}日前まで${p.cancel_pct_partial}%返金。`;\n"
"  return `<div class='cancel-policy'><h4>&#128203; キャンセルポリシー</h4><p>${txt}</p></div>`;\n"
"}\n"

"async function loadSchedulesForPlan(pid){\n"
"  const sel=document.getElementById('book-schedule');\n"
"  const waitlistSec=document.getElementById('waitlist-section');\n"
"  sel.innerHTML='<option value=\"\">読み込み中...</option>';\n"
"  waitlistSec.style.display='none';\n"
"  waitlistSec.innerHTML='';\n"
"  const d=await api('GET','/api/v1/schedules?plan_id='+pid+'&limit=60');\n"
"  const allScheds=d.schedules||[];\n"
"  const scheds=allScheds.filter(s=>s.available>0);\n"
"  if(scheds.length){\n"
"    sel.innerHTML='<option value=\"\">日程を選択</option>'+scheds.map(s=>`<option value='${s.id}'>${s.date} ${s.start_time} (残${s.available}席)</option>`).join('');\n"
"    sel.style.display='';\n"
"    firstScheduleId=scheds[0].id;\n"
"  } else {\n"
"    sel.innerHTML='<option value=\"\">空きスケジュールなし</option>';\n"
"    sel.style.display='';\n"
"    if(allScheds.length) firstScheduleId=allScheds[0].id;\n"
"    waitlistSec.style.display='block';\n"
"    waitlistSec.innerHTML="
"      '<div class=\"waitlist-box\">'"
"      +'<p>&#128274; 満席です</p>'"
"      +(isLoggedIn()"
"        ?'<button class=\"btn btn-ghost btn-sm\" onclick=\"joinWaitlist()\">&#128203; ウェイトリストに登録</button>'"
"        :'<button class=\"btn btn-ghost btn-sm\" onclick=\"openAuth(\\'login\\')\">ログインしてウェイトリストに登録</button>'"
"      )+'</div>';\n"
"  }\n"
"}\n"

"async function joinWaitlist(){\n"
"  if(!isLoggedIn()){openAuth('login');return;}\n"
"  if(!firstScheduleId){toast('スケジュールが見つかりません');return;}\n"
"  const r=await api('POST','/api/v1/waitlist',{schedule_id:firstScheduleId});\n"
"  if(r.error){\n"
"    toast('エラー: '+(r.error||'登録に失敗しました'));\n"
"  } else {\n"
"    toast('&#9989; ウェイトリストに登録しました。空きが出た際にご連絡します。');\n"
"    document.getElementById('waitlist-section').innerHTML="
"      '<div class=\"waitlist-box\"><p style=\"color:var(--success)\">&#9989; ウェイトリスト登録済み</p></div>';\n"
"  }\n"
"}\n"

"function buildParticipants(prices){\n"
"  const el=document.getElementById('book-participants');\n"
"  if(!prices.length){el.innerHTML='';return;}\n"
"  el.innerHTML=prices.map(pr=>"
"    `<div class='participants-row'>"
"<span class='label'>${pr.label} (¥${pr.price.toLocaleString()})</span>"
"<div class='qty'>"
"<button class='qty-btn' onclick='changeQty(${pr.id},-1)'>-</button>"
"<span class='qty-num' id='qty-${pr.id}'>0</span>"
"<button class='qty-btn' onclick='changeQty(${pr.id},1)'>+</button>"
"</div></div>`"
"  ).join('');\n"
"  window._prices=prices;\n"
"  updateSummary();\n"
"}\n"

"function changeQty(id,delta){\n"
"  const el=document.getElementById('qty-'+id);\n"
"  let v=parseInt(el.textContent)+delta;\n"
"  if(v<0)v=0;\n"
"  el.textContent=v;\n"
"  updateSummary();\n"
"}\n"

/* ── Coupon ── */
"async function applyCoupon(){\n"
"  const code=document.getElementById('coupon-input').value.trim();\n"
"  const msgEl=document.getElementById('coupon-msg');\n"
"  if(!code){msgEl.innerHTML='<span class=\"coupon-error\">コードを入力してください</span>';return;}\n"
"  const r=await api('GET','/api/v1/coupons/'+encodeURIComponent(code));\n"
"  if(r.error||!r.code){\n"
"    appliedCoupon=null;\n"
"    msgEl.innerHTML='<span class=\"coupon-error\">'+(r.error||'無効なクーポンコードです')+'</span>';\n"
"  } else {\n"
"    appliedCoupon=r;\n"
"    const discStr=r.discount_type==='percent'?r.discount_value+'%オフ':'¥'+r.discount_value.toLocaleString()+' 割引';\n"
"    msgEl.innerHTML='<span class=\"coupon-applied\">&#10003; '+discStr+' が適用されました</span>';\n"
"    updateSummary();\n"
"  }\n"
"}\n"

/* ── Gift Card ── */
"async function applyGiftCard(){\n"
"  const code=document.getElementById('giftcard-input').value.trim();\n"
"  const msgEl=document.getElementById('giftcard-msg');\n"
"  if(!code){msgEl.innerHTML='<span class=\"coupon-error\">コードを入力してください</span>';return;}\n"
"  const r=await api('GET','/api/v1/gift-cards/'+encodeURIComponent(code));\n"
"  if(r.error||!r.code){\n"
"    appliedGiftCard=null;\n"
"    msgEl.innerHTML='<span class=\"coupon-error\">'+(r.error||'無効なギフトカードコードです')+'</span>';\n"
"  } else {\n"
"    appliedGiftCard=r;\n"
"    msgEl.innerHTML='<span class=\"coupon-applied\">&#10003; 残高 ¥'+(r.balance||r.remaining_balance||0).toLocaleString()+' が使用可能です</span>';\n"
"    updateSummary();\n"
"  }\n"
"}\n"

"function calcDiscounts(subtotal){\n"
"  let couponDiscount=0;\n"
"  let giftDiscount=0;\n"
"  if(appliedCoupon){\n"
"    if(appliedCoupon.discount_type==='percent'){\n"
"      couponDiscount=Math.floor(subtotal*appliedCoupon.discount_value/100);\n"
"    } else {\n"
"      couponDiscount=Math.min(subtotal,appliedCoupon.discount_value||0);\n"
"    }\n"
"  }\n"
"  const afterCoupon=Math.max(0,subtotal-couponDiscount);\n"
"  if(appliedGiftCard){\n"
"    const balance=appliedGiftCard.balance||appliedGiftCard.remaining_balance||0;\n"
"    giftDiscount=Math.min(afterCoupon,balance);\n"
"  }\n"
"  return {couponDiscount,giftDiscount};\n"
"}\n"

"function updateSummary(){\n"
"  const prices=window._prices||[];\n"
"  let subtotal=0;\n"
"  let rows=prices.map(pr=>{\n"
"    const qty=parseInt((document.getElementById('qty-'+pr.id)||{textContent:'0'}).textContent);\n"
"    const sub=qty*pr.price;\n"
"    subtotal+=sub;\n"
"    return qty>0?`<div class='price-row'><span>${pr.label} x${qty}</span><span>¥${sub.toLocaleString()}</span></div>`:'';\n"
"  }).join('');\n"
"  const {couponDiscount,giftDiscount}=calcDiscounts(subtotal);\n"
"  const total=Math.max(0,subtotal-couponDiscount-giftDiscount);\n"
"  let discountRows='';\n"
"  if(couponDiscount>0) discountRows+=`<div class='price-row' style='color:var(--success);'><span>クーポン割引</span><span>-¥${couponDiscount.toLocaleString()}</span></div>`;\n"
"  if(giftDiscount>0) discountRows+=`<div class='price-row' style='color:var(--success);'><span>ギフトカード</span><span>-¥${giftDiscount.toLocaleString()}</span></div>`;\n"
"  document.getElementById('book-summary').innerHTML="
"    rows+discountRows+`<div class='price-row total'><span>合計</span><span>¥${total.toLocaleString()}</span></div>`;\n"
"  window._currentTotal=total;\n"
"}\n"

"async function doBook(){\n"
"  if(!isLoggedIn()){openAuth('login');return;}\n"
"  const sid=document.getElementById('book-schedule').value;\n"
"  if(!sid){showMsg('book-msg','err','日程を選択してください');return;}\n"
"  const prices=window._prices||[];\n"
"  const participants=prices.map(pr=>{\n"
"    const qty=parseInt((document.getElementById('qty-'+pr.id)||{textContent:'0'}).textContent);\n"
"    return{participant_type:pr.participant_type,count:qty};\n"
"  }).filter(x=>x.count>0);\n"
"  if(!participants.length){showMsg('book-msg','err','人数を1名以上選択してください');return;}\n"
"  const note=document.getElementById('book-note').value.trim();\n"
"  const bookBody={schedule_id:parseInt(sid),participants,note};\n"
"  if(appliedCoupon) bookBody.coupon_code=appliedCoupon.code;\n"
"  if(appliedGiftCard) bookBody.gift_card_code=appliedGiftCard.code;\n"
"  const r=await api('POST','/api/v1/bookings',bookBody);\n"
"  if(r.id){\n"
"    const totalPrice=window._currentTotal||0;\n"
"    if(totalPrice>0){\n"
"      const checkoutBody={\n"
"        booking_id:r.id,\n"
"        success_url:window.location.origin+'/ui',\n"
"        cancel_url:window.location.origin+'/ui'\n"
"      };\n"
"      const cs=await api('POST','/api/v1/checkout/session',checkoutBody);\n"
"      if(cs.checkout_url){\n"
"        window.location.href=cs.checkout_url;\n"
"        return;\n"
"      }\n"
"    }\n"
"    showMsg('book-msg','ok','予約が完了しました！');\n"
"    toast('&#9989; 予約完了');\n"
"  } else {\n"
"    showMsg('book-msg','err',r.error||'予約に失敗しました');\n"
"  }\n"
"}\n"

/* ── My Bookings ── */
"async function showBookings(){\n"
"  if(!isLoggedIn()){openAuth('login');return;}\n"
"  showView('bookings');\n"
"  const el=document.getElementById('my-bookings-list');\n"
"  el.innerHTML='<div class=\"spinner\"></div>';\n"
"  const d=await api('GET','/api/v1/bookings');\n"
"  const bks=d.bookings||[];\n"
"  if(!bks.length){el.innerHTML='<div class=\"empty\"><div class=\"icon\">&#128197;</div><p>まだ予約がありません</p></div>';return;}\n"
"  el.innerHTML=bks.map(bookingItem).join('');\n"
"}\n"

"function bookingItem(b){\n"
"  const statusClass={confirmed:'confirmed',cancelled:'cancelled',pending_payment:'pending'}[b.status]||'pending';\n"
"  const statusText={confirmed:'確定',cancelled:'キャンセル済',pending_payment:'支払待ち'}[b.status]||b.status;\n"
"  const canReschedule=b.status==='confirmed'||b.status==='pending_payment';\n"
"  const canCancel=b.status!=='cancelled';\n"
"  const canReview=b.status==='confirmed';\n"
"  return `<div class='booking-item'>"
"<div class='info'>"
"<div class='title'>${b.plan_title||'プラン'}</div>"
"<div class='detail'>&#128197; ${b.schedule_date} ${b.schedule_start_time||''}</div>"
"<div class='detail'>&#128180; ¥${(b.total_price||0).toLocaleString()}</div>"
"<div style='margin-top:8px;display:flex;gap:6px;flex-wrap:wrap;'>"
"<span class='badge badge-${statusClass}'>${statusText}</span>"
"${canReschedule?`<button class='btn btn-ghost btn-sm' onclick='openReschedule(\"${b.id}\",${b.plan_id})'>日程変更</button>`:''}  "
"${canReview?`<button class='btn btn-ghost btn-sm' onclick='openReview(${b.plan_id})'>レビュー</button>`:''}"
"${canCancel?`<button class='btn btn-danger btn-sm' onclick='doCancel(\"${b.id}\")'>キャンセル</button>`:''}"
"</div></div></div>`;\n"
"}\n"

"async function doCancel(id){\n"
"  if(!confirm('予約をキャンセルしますか？')) return;\n"
"  const r=await api('DELETE','/api/v1/bookings/'+id,{});\n"
"  if(r.message||!r.error){toast('キャンセルしました');showBookings();}\n"
"  else toast('エラー: '+(r.error||'不明'));\n"
"}\n"

/* ── Reschedule ── */
"async function openReschedule(bookingId,planId){\n"
"  document.getElementById('reschedule-booking-id').value=bookingId;\n"
"  document.getElementById('reschedule-plan-id').value=planId;\n"
"  const sel=document.getElementById('reschedule-schedule');\n"
"  sel.innerHTML='<option>読み込み中...</option>';\n"
"  openModal('reschedule-modal');\n"
"  const d=await api('GET','/api/v1/schedules?plan_id='+planId+'&limit=60');\n"
"  const scheds=(d.schedules||[]).filter(s=>s.available>0);\n"
"  sel.innerHTML=scheds.length?"
"    '<option value=\"\">日程を選択</option>'+scheds.map(s=>`<option value='${s.id}'>${s.date} ${s.start_time} (残${s.available}席)</option>`).join('')"
"    :'<option>空きなし</option>';\n"
"}\n"

"async function doReschedule(){\n"
"  const bid=document.getElementById('reschedule-booking-id').value;\n"
"  const sid=document.getElementById('reschedule-schedule').value;\n"
"  if(!sid){showMsg('reschedule-msg','err','日程を選択してください');return;}\n"
"  const r=await api('PATCH','/api/v1/bookings/'+bid+'/reschedule',{new_schedule_id:parseInt(sid)});\n"
"  if(r.id){toast('日程を変更しました');closeModal('reschedule-modal');showBookings();}\n"
"  else showMsg('reschedule-msg','err',r.error||'変更に失敗しました');\n"
"}\n"

/* ── Reviews ── */
"async function loadReviews(pid){\n"
"  const el=document.getElementById('reviews-section');\n"
"  const d=await api('GET','/api/v1/plans/'+pid+'/reviews?limit=10');\n"
"  const revs=d.reviews||[];\n"
"  const canReview=isLoggedIn();\n"
"  el.innerHTML=`<h3 style='font-size:18px;font-weight:700;margin-bottom:14px;'>レビュー (${d.total||revs.length}件)</h3>`"
"    +(canReview?`<button class='btn btn-ghost btn-sm' style='margin-bottom:14px;' onclick='openReview(${pid})'>&#9733; レビューを書く</button>`:'')"
"    +(revs.length?revs.map(reviewItem).join(''):'<div class=\"empty\" style=\"padding:20px 0\"><p>まだレビューがありません</p></div>');\n"
"}\n"

"function reviewItem(r){\n"
"  const stars='&#9733;'.repeat(r.rating)+'&#9734;'.repeat(5-r.rating);\n"
"  return `<div class='review-item'><div class='stars'>${stars}</div><div class='comment'>${r.comment||''}</div><div class='author'>${r.user_name||'匿名'} &middot; ${(r.created_at||'').slice(0,10)}</div></div>`;\n"
"}\n"

"function openReview(planId){\n"
"  if(!isLoggedIn()){openAuth('login');return;}\n"
"  document.getElementById('review-plan-id').value=planId;\n"
"  setStar(0);\n"
"  document.getElementById('review-comment').value='';\n"
"  showMsg('review-msg','','');\n"
"  openModal('review-modal');\n"
"}\n"

"function setStar(n){\n"
"  starRating=n;\n"
"  const spans=document.getElementById('star-picker').querySelectorAll('span');\n"
"  spans.forEach((s,i)=>s.style.color=i<n?'#f59e0b':'var(--sub)');\n"
"}\n"

"async function doReview(){\n"
"  const pid=parseInt(document.getElementById('review-plan-id').value);\n"
"  const comment=document.getElementById('review-comment').value.trim();\n"
"  if(!starRating){showMsg('review-msg','err','評価を選んでください');return;}\n"
"  const r=await api('POST','/api/v1/plans/'+pid+'/reviews',{rating:starRating,comment});\n"
"  if(r.id){toast('レビューを投稿しました');closeModal('review-modal');loadReviews(pid);}\n"
"  else showMsg('review-msg','err',r.error||'投稿に失敗しました');\n"
"}\n"

/* ── Search ── */
"function doSearch(){\n"
"  loadPlans();\n"
"}\n"

/* ── Filters ── */
"async function loadFilters(){\n"
"  const [areaData,catData]=await Promise.all([api('GET','/api/v1/areas'),api('GET','/api/v1/categories')]);\n"
"  const areaEl=document.getElementById('filter-area');\n"
"  const catEl=document.getElementById('filter-cat');\n"
"  (areaData||[]).forEach(a=>{const o=document.createElement('option');o.value=a.id;o.textContent=a.name;areaEl.appendChild(o);});\n"
"  (catData||[]).forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.name;catEl.appendChild(o);});\n"
"}\n"

/* ── Helpers ── */
"function openModal(id){document.getElementById(id).classList.add('open');}\n"
"function closeModal(id){document.getElementById(id).classList.remove('open');}\n"
"function showMsg(id,type,text){const el=document.getElementById(id);el.innerHTML=text?`<div class='msg ${type}'>${text}</div>`:'';}  \n"
"function toast(msg){\n"
"  const t=document.getElementById('toast');\n"
"  t.textContent=msg;t.classList.add('show');\n"
"  clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3000);\n"
"}\n"

/* ── Init ── */
"(async function init(){\n"
"  updateAuthUI();\n"
"  showView('home');\n"
"  await loadFilters();\n"
"  await loadPlans();\n"
"})();\n"
"</script>\n"
"</body>\n"
"</html>\n";

    mg_http_reply(c, 200,
        "Content-Type: text/html; charset=UTF-8\r\n"
        "Cache-Control: no-cache\r\n",
        "%s", HTML);
}
