    "PRAGMA journal_mode = WAL;\n"
    "PRAGMA foreign_keys = ON;\n"
    "\n"
    "-- 地域（地方 → 都道府県 → 市区）\n"
    "CREATE TABLE IF NOT EXISTS areas (\n"
    "    id        INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name      TEXT NOT NULL,\n"
    "    name_kana TEXT,\n"
    "    parent_id INTEGER REFERENCES areas(id),\n"
    "    level     INTEGER NOT NULL DEFAULT 0, -- 0=地方, 1=都道府県, 2=市区\n"
    "    slug      TEXT UNIQUE NOT NULL,\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- カテゴリ（アウトドア > ダイビング など）\n"
    "CREATE TABLE IF NOT EXISTS categories (\n"
    "    id        INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name      TEXT NOT NULL,\n"
    "    slug      TEXT UNIQUE NOT NULL,\n"
    "    parent_id INTEGER REFERENCES categories(id),\n"
    "    icon      TEXT,\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- 施設・拠点\n"
    "CREATE TABLE IF NOT EXISTS venues (\n"
    "    id           INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    name         TEXT NOT NULL,\n"
    "    description  TEXT,\n"
    "    area_id      INTEGER NOT NULL REFERENCES areas(id),\n"
    "    address      TEXT,\n"
    "    latitude     REAL,\n"
    "    longitude    REAL,\n"
    "    phone        TEXT,\n"
    "    website      TEXT,\n"
    "    images       TEXT NOT NULL DEFAULT '[]',  -- JSON array of URLs\n"
    "    review_count INTEGER NOT NULL DEFAULT 0,\n"
    "    review_avg   REAL NOT NULL DEFAULT 0.0,\n"
    "    created_at   TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- プラン（施設が提供する体験）\n"
    "CREATE TABLE IF NOT EXISTS plans (\n"
    "    id                  INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    venue_id            INTEGER NOT NULL REFERENCES venues(id),\n"
    "    category_id         INTEGER NOT NULL REFERENCES categories(id),\n"
    "    title               TEXT NOT NULL,\n"
    "    description         TEXT,\n"
    "    duration_minutes    INTEGER,\n"
    "    min_participants    INTEGER NOT NULL DEFAULT 1,\n"
    "    max_participants    INTEGER,\n"
    "    min_age             INTEGER,\n"
    "    images              TEXT NOT NULL DEFAULT '[]',  -- JSON array\n"
    "    tags                TEXT NOT NULL DEFAULT '[]',  -- JSON array\n"
    "    is_active           INTEGER NOT NULL DEFAULT 1,\n"
    "    cancel_days_full    INTEGER NOT NULL DEFAULT 7,   -- N日前まで全額返金\n"
    "    cancel_days_partial INTEGER NOT NULL DEFAULT 3,   -- N日前まで部分返金\n"
    "    cancel_pct_partial  INTEGER NOT NULL DEFAULT 50,  -- 部分返金率(%)\n"
    "    created_at          TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- 価格（大人・子供・シニア等）\n"
    "CREATE TABLE IF NOT EXISTS plan_prices (\n"
    "    id               INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    plan_id          INTEGER NOT NULL REFERENCES plans(id),\n"
    "    participant_type TEXT NOT NULL, -- 'adult', 'child', 'senior'\n"
    "    label            TEXT NOT NULL, -- '大人', '子供(3〜12歳)'\n"
    "    price            INTEGER NOT NULL, -- 円\n"
    "    created_at       TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- スケジュール（日時・空き枠）\n"
    "CREATE TABLE IF NOT EXISTS schedules (\n"
    "    id           INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    plan_id      INTEGER NOT NULL REFERENCES plans(id),\n"
    "    date         TEXT NOT NULL,       -- YYYY-MM-DD\n"
    "    start_time   TEXT NOT NULL,       -- HH:MM\n"
    "    end_time     TEXT,\n"
    "    capacity     INTEGER NOT NULL DEFAULT 10,\n"
    "    booked_count INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at   TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- ユーザー\n"
    "CREATE TABLE IF NOT EXISTS users (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    email         TEXT UNIQUE NOT NULL,\n"
    "    name          TEXT NOT NULL,\n"
    "    phone         TEXT,\n"
    "    password_hash TEXT NOT NULL,\n"
    "    failed_logins INTEGER NOT NULL DEFAULT 0,\n"
    "    locked_until  TEXT,\n"
    "    created_at    TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- 予約\n"
    "CREATE TABLE IF NOT EXISTS bookings (\n"
    "    id                       TEXT PRIMARY KEY,   -- UUID\n"
    "    user_id                  INTEGER NOT NULL REFERENCES users(id),\n"
    "    plan_id                  INTEGER NOT NULL REFERENCES plans(id),\n"
    "    schedule_id              INTEGER NOT NULL REFERENCES schedules(id),\n"
    "    status                   TEXT NOT NULL DEFAULT 'confirmed', -- pending_payment/confirmed/cancelled\n"
    "    total_price              INTEGER NOT NULL,\n"
    "    note                     TEXT,\n"
    "    stripe_payment_intent_id TEXT,   -- pi_xxx... (Stripe PaymentIntent ID)\n"
    "    created_at               TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- 予約参加者内訳\n"
    "CREATE TABLE IF NOT EXISTS booking_participants (\n"
    "    id               INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    booking_id       TEXT NOT NULL REFERENCES bookings(id),\n"
    "    participant_type TEXT NOT NULL,\n"
    "    label            TEXT NOT NULL,\n"
    "    count            INTEGER NOT NULL,\n"
    "    unit_price       INTEGER NOT NULL\n"
    ");\n"
    "\n"
    "-- 口コミ・レビュー\n"
    "CREATE TABLE IF NOT EXISTS reviews (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    booking_id TEXT REFERENCES bookings(id),\n"
    "    user_id    INTEGER NOT NULL REFERENCES users(id),\n"
    "    plan_id    INTEGER NOT NULL REFERENCES plans(id),\n"
    "    rating     INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),\n"
    "    comment    TEXT,\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- お気に入り（プランのブックマーク）\n"
    "CREATE TABLE IF NOT EXISTS bookmarks (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    user_id    INTEGER NOT NULL REFERENCES users(id),\n"
    "    plan_id    INTEGER NOT NULL REFERENCES plans(id),\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now')),\n"
    "    UNIQUE(user_id, plan_id)\n"
    ");\n"
    "\n"
    "-- パスワードリセットトークン（1時間有効）\n"
    "CREATE TABLE IF NOT EXISTS password_reset_tokens (\n"
    "    token      TEXT PRIMARY KEY,\n"
    "    user_id    INTEGER NOT NULL REFERENCES users(id),\n"
    "    expires_at TEXT NOT NULL,\n"
    "    used       INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- レビュー更新時に venue の集計を自動更新\n"
    "CREATE TRIGGER IF NOT EXISTS update_venue_review_stats\n"
    "AFTER INSERT ON reviews\n"
    "BEGIN\n"
    "    UPDATE venues SET\n"
    "        review_count = (SELECT COUNT(*) FROM reviews r JOIN plans p ON p.id = r.plan_id WHERE p.venue_id = (SELECT venue_id FROM plans WHERE id = NEW.plan_id)),\n"
    "        review_avg   = (SELECT ROUND(AVG(r.rating), 1) FROM reviews r JOIN plans p ON p.id = r.plan_id WHERE p.venue_id = (SELECT venue_id FROM plans WHERE id = NEW.plan_id))\n"
    "    WHERE id = (SELECT venue_id FROM plans WHERE id = NEW.plan_id);\n"
    "END;\n"
    "\n"
    "-- レビュー削除時に venue の集計を自動更新\n"
    "CREATE TRIGGER IF NOT EXISTS update_venue_review_stats_delete\n"
    "AFTER DELETE ON reviews\n"
    "BEGIN\n"
    "    UPDATE venues SET\n"
    "        review_count = COALESCE((SELECT COUNT(*) FROM reviews r JOIN plans p ON p.id = r.plan_id WHERE p.venue_id = (SELECT venue_id FROM plans WHERE id = OLD.plan_id)), 0),\n"
    "        review_avg   = COALESCE((SELECT ROUND(AVG(r.rating), 1) FROM reviews r JOIN plans p ON p.id = r.plan_id WHERE p.venue_id = (SELECT venue_id FROM plans WHERE id = OLD.plan_id)), 0.0)\n"
    "    WHERE id = (SELECT venue_id FROM plans WHERE id = OLD.plan_id);\n"
    "END;\n"
    "\n"
    "-- スケジュール booked_count 自動更新\n"
    "CREATE TRIGGER IF NOT EXISTS update_schedule_booked_count\n"
    "AFTER INSERT ON booking_participants\n"
    "BEGIN\n"
    "    UPDATE schedules SET\n"
    "        booked_count = booked_count + NEW.count\n"
    "    WHERE id = (SELECT schedule_id FROM bookings WHERE id = NEW.booking_id);\n"
    "END;\n"
    "\n"
    "-- ウェイトリスト（満席時の待機リスト）\n"
    "CREATE TABLE IF NOT EXISTS waitlist (\n"
    "    id          INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    user_id     INTEGER NOT NULL REFERENCES users(id),\n"
    "    schedule_id INTEGER NOT NULL REFERENCES schedules(id),\n"
    "    notified    INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at  TEXT NOT NULL DEFAULT (datetime('now')),\n"
    "    UNIQUE(user_id, schedule_id)\n"
    ");\n"
    "\n"
    "-- Stripe webhook イベント冪等性管理\n"
    "CREATE TABLE IF NOT EXISTS webhook_events (\n"
    "    event_id     TEXT PRIMARY KEY,  -- Stripe evt_xxx\n"
    "    processed_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- JWT ブラックリスト（ログアウト・パスワード変更後のトークン無効化）\n"
    "CREATE TABLE IF NOT EXISTS jwt_blocklist (\n"
    "    jti        TEXT PRIMARY KEY,  -- トークン署名（.以降の最終パート）\n"
    "    expires_at TEXT NOT NULL,\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- FTS5 全文検索（plans の title / description を索引化）\n"
    "CREATE VIRTUAL TABLE IF NOT EXISTS plans_fts\n"
    "    USING fts5(title, description, content='plans', content_rowid='id');\n"
    "\n"
    "-- 管理者操作監査ログ\n"
    "CREATE TABLE IF NOT EXISTS audit_logs (\n"
    "    id          INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    ts          TEXT NOT NULL DEFAULT (datetime('now')),\n"
    "    actor       TEXT NOT NULL DEFAULT 'admin',\n"
    "    action      TEXT NOT NULL,\n"
    "    target_type TEXT,\n"
    "    target_id   TEXT,\n"
    "    detail      TEXT,\n"
    "    ip          TEXT\n"
    ");\n"
    "\n"
    "-- クーポン・プロモコード\n"
    "CREATE TABLE IF NOT EXISTS coupons (\n"
    "    id             INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    code           TEXT UNIQUE NOT NULL COLLATE NOCASE,\n"
    "    description    TEXT,\n"
    "    discount_type  TEXT NOT NULL DEFAULT 'percent', -- 'percent' | 'fixed'\n"
    "    discount_value INTEGER NOT NULL,                -- % または円\n"
    "    max_uses       INTEGER,                         -- NULL=無制限\n"
    "    used_count     INTEGER NOT NULL DEFAULT 0,\n"
    "    expires_at     TEXT,                            -- NULL=無期限\n"
    "    is_active      INTEGER NOT NULL DEFAULT 1,\n"
    "    created_at     TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- パートナー向け Webhook エンドポイント\n"
    "CREATE TABLE IF NOT EXISTS webhook_endpoints (\n"
    "    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    url        TEXT NOT NULL,\n"
    "    secret     TEXT NOT NULL,               -- HMAC 署名シークレット\n"
    "    events     TEXT NOT NULL DEFAULT '[]',  -- JSON array: [\"booking.created\", ...]\n"
    "    is_active  INTEGER NOT NULL DEFAULT 1,\n"
    "    created_at TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- Webhook 配信ログ\n"
    "CREATE TABLE IF NOT EXISTS webhook_deliveries (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    endpoint_id   INTEGER NOT NULL REFERENCES webhook_endpoints(id),\n"
    "    event         TEXT NOT NULL,\n"
    "    payload       TEXT NOT NULL,\n"
    "    response_code INTEGER,\n"
    "    delivered_at  TEXT NOT NULL DEFAULT (datetime('now')),\n"
    "    success       INTEGER NOT NULL DEFAULT 0\n"
    ");\n"
    "\n"
    "-- プラン追加画像（メイン images JSON に加えて個別管理）\n"
    "CREATE TABLE IF NOT EXISTS plan_images (\n"
    "    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "    plan_id       INTEGER NOT NULL REFERENCES plans(id),\n"
    "    url           TEXT NOT NULL,\n"
    "    display_order INTEGER NOT NULL DEFAULT 0,\n"
    "    created_at    TEXT NOT NULL DEFAULT (datetime('now'))\n"
    ");\n"
    "\n"
    "-- FTS5 同期トリガー\n"
    "CREATE TRIGGER IF NOT EXISTS plans_ai AFTER INSERT ON plans BEGIN\n"
    "    INSERT INTO plans_fts(rowid, title, description)\n"
    "        VALUES (new.id, new.title, new.description);\n"
    "END;\n"
    "\n"
    "CREATE TRIGGER IF NOT EXISTS plans_ad AFTER DELETE ON plans BEGIN\n"
    "    INSERT INTO plans_fts(plans_fts, rowid, title, description)\n"
    "        VALUES ('delete', old.id, old.title, old.description);\n"
    "END;\n"
    "\n"
    "CREATE TRIGGER IF NOT EXISTS plans_au AFTER UPDATE ON plans BEGIN\n"
    "    INSERT INTO plans_fts(plans_fts, rowid, title, description)\n"
    "        VALUES ('delete', old.id, old.title, old.description);\n"
    "    INSERT INTO plans_fts(rowid, title, description)\n"
    "        VALUES (new.id, new.title, new.description);\n"
    "END;\n"
